version: 0.2

env:
  parameter-store:
    AMPLIFY_ACCOUNT_NUMBER_PROD: "arn-amplify-poc-prod"
    ENV: "envFromCrossAccAmplify"
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  build:
    commands:
      - echo Build started...
      - assumes_role=`aws sts assume-role --role-arn "arn:aws:iam::$AMPLIFY_ACCOUNT_NUMBER_PROD:role/CrossAccountRole" --role-session-name int`
      - AWS_ACCESS_KEY_ID=`echo $assumes_role | jq -r .Credentials.AccessKeyId`
      - AWS_SECRET_ACCESS_KEY=`echo $assumes_role | jq -r .Credentials.SecretAccessKey`
      - AWS_SESSION_TOKEN=`echo $assumes_role | jq -r .Credentials.SessionToken`
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set default.region $AWS_REGION
      - aws configure set aws_session_token $AWS_SESSION_TOKEN
      - sh ./amplifyPush.sh -s -e $ENV
      - amplify env list
      - amplify publish
      - echo Build finished on `date`
artifacts:
  files:
    - "**/*"
